# Generated by Django 5.1.3 on 2024-11-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quantity", models.IntegerField(default=0)),
                ("unit_price", models.IntegerField(default=0)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gram"),
                            ("kg", "Kilogram"),
                            ("l", "Liter"),
                            ("ml", "Milliliter"),
                            ("tsp", "Teaspoon"),
                            ("tbsp", "Tablespoon"),
                            ("cup", "Cup"),
                            ("pc", "Piece"),
                            ("pinch", "Pinch"),
                        ],
                        default="g",
                        max_length=5,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
