# Generated by Django 5.1.3 on 2024-11-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_menu"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Menu",
            new_name="MenuItem",
        ),
    ]
